# Generated by Django 2.2.17 on 2021-03-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_category_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='picture',
            field=models.ImageField(blank=True, default=None, upload_to='lecturer_images'),
        ),
    ]
