# Generated by Django 2.2.17 on 2021-03-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_auto_20210322_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pageowner',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='pageowner',
            field=models.CharField(max_length=30),
        ),
    ]
